namespace Domain.Enums
{
    public enum EventType
    {
        NewMissionStarted = 1,
        MissionCanceledFromServer = 2,
        TheAgentIsInFailureZone = 3,
        TheAgentFoundTheFailureLocation = 4,
        GpsIsTurnedOff = 5,
        GpsIsTurnedOn = 6,
        GpsIsStillOff = 7,
        MissionTimedOut = 8,
        LowBattery = 9,
        LowSpeed  = 10,
        GotOutOfFailureZone = 11,
        GotOutOfDepoZone = 12,
        ResumedAfterPhoneRestart = 13,
        MissionFinishedAutomatically = 14,
        TheFailureLocationDetectedAutomatically = 15,
        IncomingCallFromWhitelist = 16,
        OutgoingCallToWhitelist = 17,
        InvalidIncomingCall= 18,
        InvalidOutgoingCall = 19,
        IncomingSMSFromWhitelist = 20,
        OutgoingSMSToWhitelist = 21,
        InvalidIncomingSMS= 22,
        InvalidOutgoingSMS = 23,
        AgentLoggedOut = 24,
        AgentLoggedIn = 25,
        AgentIsNotMoving = 26,
        AgentCameBackToTheDepo = 27,
        OTDRTestCaptured = 28,
        OTDRTestIsNotCaptured = 29,
        TheAgentStartMoving = 30,
        MissionEdited = 31,
        MissionFinished = 32,
        MissionCanceledByAgent = 33,
        StatusCaptured = 34,
    }
}